[build]
  command = "python manage.py migrate && gunicorn myportfolio.wsgi"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.8"

[[plugins]]
  package = "@netlify/plugin-cache"
  config = {
    command = "pip install -r requirements.txt"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
